# Generated by Django 5.0.3 on 2024-06-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_number_obfuscated',
            field=models.CharField(max_length=19),
        ),
    ]
