# Generated by Django 5.0.3 on 2024-06-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_payment_card_number_obfuscated'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cvv',
            field=models.CharField(default=333, max_length=3),
            preserve_default=False,
        ),
    ]
