# Generated by Django 5.0.3 on 2024-06-12 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_payment_cvv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='cvv',
        ),
    ]
