# Generated by Django 5.0.3 on 2024-06-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_payment_cvv'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='expiry_date',
            field=models.CharField(default='01/2026', max_length=7),
        ),
    ]
