from django.urls import path
from shop import views

urlpatterns = [
    path('products', views.product_list),
    path('products/<int:pk>', views.single_product),
    path('deliveries', views.delivery_list),
    path('deliveries/<int:pk>', views.single_delivery),
    path('deliveries/<int:id>', views.user_delivery),
    path('types', views.product_type),
    path('categories', views.categories_list),
    path('productvariants', views.product_variants),
    path('bestsellers', views.bestsellers),
    path('login', views.user_login),
    path('register', views.register),
    path('add_to_basket', views.add_to_basket),
    path('add-promotion-bundle-to-basket', views.add_promotion_bundle_to_basket),
    path('basket/', views.user_basket),
    path('basket/<int:user_id>', views.user_basket),
    path('update_basket', views.update_basket),
    path('merge-baskets', views.merge_baskets),
    path('create-product', views.create_product),
    path('create-order', views.create_order),
    path('orders', views.order_list),
    path('order/<int:pk>', views.order),
    path('reviews/<int:id>', views.review_list),
    path('update-order', views.update_order),
    path('rate-product', views.rate_product),
    path('apply-voucher', views.apply_voucher),
    path('user-vouchers/<int:user_id>', views.user_vouchers),
    path('user-orders/<int:user_id>', views.user_orders),
    path('send-test-email', views.send_test_email),
    path('change-password/<int:user_id>', views.change_password),
    path('send-recovery-code', views.send_recovery_code),
    path('recover-password', views.recover_password),
    path('set-password', views.set_recovered_password),
    path('create-payment', views.create_payment ),
    path('set-default-delivery', views.set_default_delivery),
    path('get-default-delivery/<int:pk>', views.get_default_delivery),
    path('product-promotions', views.promotions_list),
    path('create-bundle', views.create_promotion_bundle),
    path('users', views.user_list),
    path('email-customer', views.email_customer),
    path('payments', views.payment_list),
    path('popular-types', views.popular_types),
    path('popular-products', views.popular_products),
    path('notifications', views.unread_notifications),
    path('notification-read', views.notification_read),
    path('mark-all-as-read', views.mark_all_as_read),
    path('all-notifications', views.all_notifications)
]